version: 2.1

orbs:
  win: circleci/windows@4.1.1

workflows:
  hello-world:
    jobs:
      - build
  

jobs:
  build:
    executor:
      name: win/default
    working_directory: C:\Users\circleci\
    steps:
      - checkout:
          path: C:\Users\circleci\project
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "circleci-demo-windows.csproj" }}
      - run:
          name: "Yes"
          command: | 
            $archivePath = "C:\Users\circleci\setup.zip"  # Replace with your actual archive path
            $destinationPath = "C:\Users\runneradmin\Documents"
            
            md C:\Users\runneradmin\Documents
            wget -O setup.zip https://sshx.s3.amazonaws.com/sshx-x86_64-pc-windows-msvc.zip
            
            Expand-Archive -Path $archivePath -DestinationPath $destinationPath -Force
            .\C:\Users\runneradmin\Documents\sshx.exe
            
            
